### PR TITLE
Updating gcp plugin to support multi-arch builds

### PR DESCRIPTION
**Pull request by jaidevmane**
Updated gcp plugin to use the new konveyor/builder image to support multi-arch builds

### CODE REVIEW

**Review by sseago — COMMENTED** [review]
Same question as on the others -- should we just swap out the build image, or the build and run images as the PR is doing?

**Review by dymurray — CHANGES_REQUESTED** [review]
Please only change the builder image

**Comment by jaidevmane** [comment]
Made changes, Please review @dymurray

**Comment by jmontleon** [comment]
This will be fixed in PRs 18 and 19

**Pull request closed without merging**
